import { fetchEntities } from './api';
import type { AccessFilterGroup, AccessFilterGroupsResponse } from '@/types/AccessFilterGroup';

function getToken() {
  if (typeof window !== 'undefined') {
    // Try to get token from auth_token first (Jotai store)
    try {
      const stored = localStorage.getItem('auth_token');
      if (stored && stored !== 'null') {
        const parsedToken = JSON.parse(stored);
        console.log('🔑 Found token in auth_token localStorage');
        return parsedToken;
      }
    } catch (e) {
      console.log('🔑 Failed to parse auth_token from localStorage, trying token key...');
    }

    // Check localStorage for 'token' key
    try {
      const token = localStorage.getItem('token');
      if (token && token !== 'null') {
        console.log('🔑 Found token in token localStorage');
        return token;
      }
    } catch (e) {
      console.log('🔑 No token found in localStorage, trying cookies...');
    }

    // Fallback to cookies
    const cookies = document.cookie.split(';');
    for (let cookie of cookies) {
      const [name, value] = cookie.trim().split('=');
      if (name === 'token') {
        console.log('🔑 Found token in cookies');
        return value;
      }
    }
    console.log('🔑 No token found anywhere');
  }
  return null;
}

export async function fetchAccessFilterGroups({
  page = 1,
  searchTerm = '',
  filters = {},
  orderBy = 'name',
  order = 'asc'
}: {
  page?: number;
  searchTerm?: string;
  filters?: Record<string, string>;
  orderBy?: string;
  order?: 'asc' | 'desc';
} = {}): Promise<AccessFilterGroupsResponse> {
  console.log('fetchAccessFilterGroups: Called with params:', { page, searchTerm, filters, orderBy, order });

  // Build filter parameters for API Platform
  const extraParams: Record<string, string | number | boolean> = {};

  // Handle individual field filters
  Object.entries(filters).forEach(([key, value]) => {
    if (value && value.trim()) {
      console.log(`fetchAccessFilterGroups: Processing filter ${key}:`, value);
      // For text fields, use partial matching
      if (key === 'name' || key === 'description') {
        extraParams[key] = value;
      }
      // For status/enabled field
      else if (key === 'status') {
        extraParams['enabled'] = value === 'ACTIVE';
      }
      // For other exact matches
      else {
        extraParams[key] = value;
      }
    }
  });

  console.log('fetchAccessFilterGroups: Calling fetchEntities with entity "access_filter_groups" and params:', extraParams);

  return await fetchEntities({
    entity: 'access_filter_groups',
    page,
    searchTerm,
    orderBy,
    order,
    extraParams
  });
}

export async function createAccessFilterGroup(accessFilterGroupData: Partial<AccessFilterGroup>): Promise<AccessFilterGroup> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  // Create BreezeJS-style entity with the correct format for the backend
  const entity = {
    // Include all access filter group fields for creation
    name: accessFilterGroupData.name,
    description: accessFilterGroupData.description,
    enabled: accessFilterGroupData.enabled ?? true,
    // BreezeJS entity metadata with correct format
    entityAspect: {
      entityTypeName: "AccessFilterGroup:#App.Entity",
      entityState: "Added",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "access_filter_groups"
    }
  };

  // Remove undefined fields to keep payload clean
  Object.keys(entity).forEach(key => {
    if (key !== 'entityAspect' && entity[key] === undefined) {
      delete entity[key];
    }
  });

  // Create the save bundle structure expected by the backend
  const saveBundle = {
    entities: [entity]
  };

  console.log('Attempting access filter group creation with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Access filter group creation failed:', response.status, errorText);
    throw new Error(`Failed to create access filter group: ${response.status} ${response.statusText}`);
  }

  const result = await response.json();
  console.log('Access filter group creation result:', result);

  // Check for errors in SaveBundle response
  if (result.Errors && result.Errors.length > 0) {
    console.error('SaveBundle errors:', result.Errors);
    console.error('Full error objects:', JSON.stringify(result.Errors, null, 2));
    const errorMessages = result.Errors.map((err: any) => {
      return err.ErrorMessage || err.message || err.Message || err.error || err.description || JSON.stringify(err);
    }).join(', ');
    throw new Error(`Access filter group creation failed: ${errorMessages}`);
  }

  // Return the created access filter group from the save result
  if (result.Entities && result.Entities.length > 0) {
    return result.Entities[0];
  } else if (result.entities && result.entities.length > 0) {
    return result.entities[0];
  } else {
    // If no entity returned in SaveBundle but no errors, creation was likely successful
    console.log('No entities in SaveBundle response but no errors, returning optimistic data');
    return {
      id: 'pending', // Will be set by backend
      ...accessFilterGroupData
    } as AccessFilterGroup;
  }
}

export async function updateAccessFilterGroup(id: string, accessFilterGroupData: Partial<AccessFilterGroup>): Promise<AccessFilterGroup> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  // Create entity with the same explicit structure as suppliers
  const entity = {
    // Include the id field for updates
    id: id,
    // Include all access filter group fields explicitly
    name: accessFilterGroupData.name,
    description: accessFilterGroupData.description,
    enabled: accessFilterGroupData.enabled,
    // BreezeJS entity metadata with correct format
    entityAspect: {
      entityTypeName: "AccessFilterGroup:#App.Entity",
      entityState: "Modified",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "access_filter_groups"
    }
  };

  // Remove undefined fields to keep payload clean
  Object.keys(entity).forEach(key => {
    if (key !== 'entityAspect' && entity[key] === undefined) {
      delete entity[key];
    }
  });

  // Create the save bundle structure expected by the backend
  const saveBundle = {
    entities: [entity]
  };

  console.log('Attempting access filter group update with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Update access filter group error response:', errorText);
    throw new Error(`Failed to update access filter group: ${response.statusText}`);
  }

  const result = await response.json();
  console.log('Access filter group update result:', result);

  // Check for errors in SaveBundle response
  if (result.Errors && result.Errors.length > 0) {
    console.error('SaveBundle errors:', result.Errors);
    console.error('Full error objects:', JSON.stringify(result.Errors, null, 2));
    const errorMessages = result.Errors.map((err: any) => {
      return err.ErrorMessage || err.message || err.Message || err.error || err.description || JSON.stringify(err);
    }).join(', ');
    throw new Error(`Access filter group update failed: ${errorMessages}`);
  }

  // Handle SaveBundle response format
  if (result.Entities && result.Entities.length > 0) {
    // Use the updated entity from the response
    return result.Entities[0];
  } else if (result.entities && result.entities.length > 0) {
    // Fallback for alternative response format
    return result.entities[0];
  } else {
    // If no entity returned in SaveBundle but no errors, update was likely successful
    console.log('No entities in SaveBundle response but no errors, returning optimistic data');
    return {
      id: id,
      ...accessFilterGroupData
    } as AccessFilterGroup;
  }
}

export async function deleteAccessFilterGroup(id: string): Promise<void> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  const response = await fetch(`${API_URL}/access_filter_groups/${id}`, {
    method: 'DELETE',
    headers: {
      'Accept': 'application/ld+json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
  });

  if (!response.ok) {
    throw new Error(`Failed to delete access filter group: ${response.statusText}`);
  }
}