import { fetchEntities } from './api';
import type { CountryManager, CountryManagersResponse } from '@/types/CountryManager';
import { logger } from '@/utils/logger';

// Re-export types for component usage
export type { CountryManager, CountryManagersResponse };

function getToken() {
  if (typeof window !== 'undefined') {
    // Try to get token from auth_token first (Jotai store)
    try {
      const stored = localStorage.getItem('auth_token');
      if (stored && stored !== 'null') {
        const parsedToken = JSON.parse(stored);
        logger.log('🔑 Found token in auth_token localStorage');
        return parsedToken;
      }
    } catch (e) {
      logger.log('🔑 Failed to parse auth_token from localStorage, trying token key...');
    }

    // Check localStorage for 'token' key
    try {
      const token = localStorage.getItem('token');
      if (token && token !== 'null') {
        logger.log('🔑 Found token in token localStorage');
        return token;
      }
    } catch (e) {
      logger.log('🔑 No token found in localStorage, trying cookies...');
    }

    // Fallback to cookies
    const cookies = document.cookie.split(';');
    for (let cookie of cookies) {
      const [name, value] = cookie.trim().split('=');
      if (name === 'token') {
        logger.log('🔑 Found token in cookies');
        return value;
      }
    }
    logger.log('🔑 No token found anywhere');
  }
  return null;
}

export async function fetchCountryManagers({
  page = 1,
  searchTerm = '',
  filters = {},
  orderBy = 'country',
  order = 'asc'
}: {
  page?: number;
  searchTerm?: string;
  filters?: Record<string, string>;
  orderBy?: string;
  order?: 'asc' | 'desc';
} = {}): Promise<CountryManagersResponse> {
  logger.log('fetchCountryManagers: Called with params:', { page, searchTerm, filters, orderBy, order });

  // Build filter parameters for API Platform
  const extraParams: Record<string, string | number | boolean> = {};

  // Handle individual field filters
  Object.entries(filters).forEach(([key, value]) => {
    if (value && value.trim()) {
      logger.log(`fetchCountryManagers: Processing filter ${key}:`, value);
      // For text fields, use partial matching
      if (key === 'country' || key === 'managerName' || key === 'email' || key === 'region') {
        extraParams[key] = value;
      }
      // For status/enabled field
      else if (key === 'status') {
        extraParams['enabled'] = value === 'ACTIVE';
      }
      // For other exact matches
      else {
        extraParams[key] = value;
      }
    }
  });

  logger.log('fetchCountryManagers: Calling fetchEntities with entity "country_managers" and params:', extraParams);

  return await fetchEntities({
    entity: 'country_managers',
    page,
    searchTerm,
    orderBy,
    order,
    extraParams
  });
}

export async function createCountryManager(countryManagerData: Partial<CountryManager>): Promise<CountryManager> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  // Create BreezeJS-style entity with the correct format for the backend
  const entity = {
    // Include all country manager fields for creation
    country: countryManagerData.country,
    managerName: countryManagerData.managerName,
    email: countryManagerData.email,
    phone: countryManagerData.phone,
    region: countryManagerData.region,
    enabled: countryManagerData.enabled ?? true,
    // BreezeJS entity metadata with correct format
    entityAspect: {
      entityTypeName: "CountryManager:#App.Entity",
      entityState: "Added",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "country_managers"
    }
  };

  // Remove undefined fields to keep payload clean
  Object.keys(entity).forEach(key => {
    if (key !== 'entityAspect' && (entity as any)[key] === undefined) {
      delete (entity as any)[key];
    }
  });

  // Create the save bundle structure expected by the backend
  const saveBundle = {
    entities: [entity]
  };

  logger.log('Attempting country manager creation with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    logger.error('Country manager creation failed:', response.status, errorText);
    throw new Error(`Failed to create country manager: ${response.status} ${response.statusText}`);
  }

  const result = await response.json();
  logger.log('Country manager creation result:', result);

  // Check for errors in SaveBundle response
  if (result.Errors && result.Errors.length > 0) {
    logger.error('SaveBundle errors:', result.Errors);
    logger.error('Full error objects:', JSON.stringify(result.Errors, null, 2));
    const errorMessages = result.Errors.map((err: any) => {
      return err.ErrorMessage || err.message || err.Message || err.error || err.description || JSON.stringify(err);
    }).join(', ');
    throw new Error(`Country manager creation failed: ${errorMessages}`);
  }

  // Return the created country manager from the save result
  if (result.Entities && result.Entities.length > 0) {
    return result.Entities[0];
  } else if (result.entities && result.entities.length > 0) {
    return result.entities[0];
  } else {
    // If no entity returned in SaveBundle but no errors, creation was likely successful
    logger.log('No entities in SaveBundle response but no errors, returning optimistic data');
    return {
      id: 'pending', // Will be set by backend
      ...countryManagerData
    } as CountryManager;
  }
}

export async function updateCountryManager(id: string, countryManagerData: Partial<CountryManager>): Promise<CountryManager> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  // Create entity with the same explicit structure as suppliers
  const entity = {
    // Include the id field for updates
    id: id,
    // Include all country manager fields explicitly
    country: countryManagerData.country,
    managerName: countryManagerData.managerName,
    email: countryManagerData.email,
    phone: countryManagerData.phone,
    region: countryManagerData.region,
    enabled: countryManagerData.enabled,
    // BreezeJS entity metadata with correct format
    entityAspect: {
      entityTypeName: "CountryManager:#App.Entity",
      entityState: "Modified",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "country_managers"
    }
  };

  // Remove undefined fields to keep payload clean
  Object.keys(entity).forEach(key => {
    if (key !== 'entityAspect' && (entity as any)[key] === undefined) {
      delete (entity as any)[key];
    }
  });

  // Create the save bundle structure expected by the backend
  const saveBundle = {
    entities: [entity]
  };

  logger.log('Attempting country manager update with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    logger.error('Update country manager error response:', errorText);
    throw new Error(`Failed to update country manager: ${response.statusText}`);
  }

  const result = await response.json();
  logger.log('Country manager update result:', result);

  // Check for errors in SaveBundle response
  if (result.Errors && result.Errors.length > 0) {
    logger.error('SaveBundle errors:', result.Errors);
    logger.error('Full error objects:', JSON.stringify(result.Errors, null, 2));
    const errorMessages = result.Errors.map((err: any) => {
      return err.ErrorMessage || err.message || err.Message || err.error || err.description || JSON.stringify(err);
    }).join(', ');
    throw new Error(`Country manager update failed: ${errorMessages}`);
  }

  // Handle SaveBundle response format
  if (result.Entities && result.Entities.length > 0) {
    // Use the updated entity from the response
    return result.Entities[0];
  } else if (result.entities && result.entities.length > 0) {
    // Fallback for alternative response format
    return result.entities[0];
  } else {
    // If no entity returned in SaveBundle but no errors, update was likely successful
    logger.log('No entities in SaveBundle response but no errors, returning optimistic data');
    return {
      id: id,
      ...countryManagerData
    } as CountryManager;
  }
}

export async function deleteCountryManager(id: string): Promise<void> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  const response = await fetch(`${API_URL}/country_managers/${id}`, {
    method: 'DELETE',
    headers: {
      'Accept': 'application/ld+json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
  });

  if (!response.ok) {
    throw new Error(`Failed to delete country manager: ${response.statusText}`);
  }
}