import { fetchEntities } from './api';

export interface Extra {
  id: string;
  name: string;
  sequence?: number;
  active?: boolean;
  price?: number;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ExtrasResponse {
  'hydra:member': Extra[];
  'hydra:totalItems': number;
  'hydra:view'?: {
    '@id': string;
    'hydra:first'?: string;
    'hydra:last'?: string;
    'hydra:next'?: string;
    'hydra:previous'?: string;
  };
}

export async function fetchExtras({
  page = 1,
  searchTerm = '',
  filters = {},
  orderBy = 'sequence',
  order = 'asc'
}: {
  page?: number;
  searchTerm?: string;
  filters?: Record<string, string>;
  orderBy?: string;
  order?: 'asc' | 'desc';
} = {}): Promise<ExtrasResponse> {
  console.log('fetchExtras: Called with params:', { page, searchTerm, filters, orderBy, order });
  
  // Build filter parameters for API Platform
  const extraParams: Record<string, string | number | boolean> = {};
  
  // Handle individual field filters
  Object.entries(filters).forEach(([key, value]) => {
    if (value && value.trim()) {
      console.log(`fetchExtras: Processing filter ${key}:`, value);
      // For text fields, use partial matching with API Platform filters
      if (key === 'name') {
        extraParams['name[contains]'] = value;
      } else if (key === 'description') {
        extraParams['description[contains]'] = value;
      } else if (key === 'active') {
        extraParams['active'] = value === 'true';
      } else if (key === 'sequence') {
        extraParams['sequence'] = parseInt(value);
      } else if (key === 'price') {
        extraParams['price'] = parseFloat(value);
      }
      // For other exact matches
      else {
        extraParams[key] = value;
      }
    }
  });

  console.log('fetchExtras: Calling fetchEntities with entity "extras" and params:', extraParams);

  return await fetchEntities({
    entity: 'extras',
    page,
    searchTerm,
    orderBy,
    order,
    extraParams
  });
}

function getToken() {
  if (typeof window !== 'undefined') {
    // Try to get token from auth_token first (Jotai store)
    try {
      const stored = localStorage.getItem('auth_token');
      if (stored && stored !== 'null') {
        const parsedToken = JSON.parse(stored);
        return parsedToken;
      }
    } catch (e) {
      // Fallback to token key
    }

    // Check localStorage for 'token' key
    try {
      const token = localStorage.getItem('token');
      if (token && token !== 'null') {
        return token;
      }
    } catch (e) {
      // Continue to cookies
    }

    // Fallback to cookies
    const cookies = document.cookie.split(';');
    for (let cookie of cookies) {
      const [name, value] = cookie.trim().split('=');
      if (name === 'token') {
        return value;
      }
    }
  }
  return null;
}

export async function createExtra(extraData: Partial<Extra>): Promise<Extra> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  // Create BreezeJS-style entity with the correct format for the backend
  const entity = {
    name: extraData.name,
    sequence: extraData.sequence || 0,
    active: extraData.active ?? true,
    price: extraData.price,
    description: extraData.description,
    // BreezeJS entity metadata
    entityAspect: {
      entityTypeName: "Extra:#App.Entity.Modelling",
      entityState: "Added",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "extras"
    }
  };

  // Remove undefined fields
  Object.keys(entity).forEach(key => {
    if (key !== 'entityAspect' && entity[key] === undefined) {
      delete entity[key];
    }
  });

  // Create the save bundle structure expected by the backend
  const saveBundle = {
    entities: [entity]
  };

  console.log('Attempting extra creation with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Extra creation failed:', errorText);
    throw new Error(`Failed to create extra: ${response.statusText}`);
  }

  const result = await response.json();
  console.log('Extra creation result:', result);

  // Return the first entity from the response
  return result.Entities?.[0] || result.entities?.[0] || result;
}

export async function updateExtra(id: string, extraData: Partial<Extra>): Promise<Extra> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  // Create BreezeJS-style entity with the correct format for the backend
  const entity = {
    id: id,
    name: extraData.name,
    sequence: extraData.sequence || 0,
    active: extraData.active ?? true,
    price: extraData.price,
    description: extraData.description,
    // BreezeJS entity metadata
    entityAspect: {
      entityTypeName: "Extra:#App.Entity.Modelling",
      entityState: "Modified",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "extras"
    }
  };

  // Remove undefined fields
  Object.keys(entity).forEach(key => {
    if (key !== 'entityAspect' && entity[key] === undefined) {
      delete entity[key];
    }
  });

  // Create the save bundle structure expected by the backend
  const saveBundle = {
    entities: [entity]
  };

  console.log('Attempting extra update with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Extra update failed:', errorText);
    throw new Error(`Failed to update extra: ${response.statusText}`);
  }

  const result = await response.json();
  console.log('Extra update result:', result);

  // Return the first entity from the response
  return result.Entities?.[0] || result.entities?.[0] || result;
}

export async function deleteExtra(id: string): Promise<void> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();
  
  const response = await fetch(`${API_URL}/extras/${id}`, {
    method: 'DELETE',
    headers: {
      'Accept': 'application/ld+json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
  });

  if (!response.ok) {
    throw new Error(`Failed to delete extra: ${response.statusText}`);
  }
}