import { fetchEntities } from './api';

export interface Model {
  id: string;
  name: string;
  brandName: string;
  brand?: {
    id: string;
    name: string;
  };
  sequence: number;
  active: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface ModelsResponse {
  'hydra:member': Model[];
  'hydra:totalItems': number;
  'hydra:view'?: {
    '@id': string;
    'hydra:first'?: string;
    'hydra:last'?: string;
    'hydra:next'?: string;
    'hydra:previous'?: string;
  };
}

export async function fetchModels({
  page = 1,
  searchTerm = '',
  filters = {},
  orderBy = 'sequence',
  order = 'asc'
}: {
  page?: number;
  searchTerm?: string;
  filters?: Record<string, string>;
  orderBy?: string;
  order?: 'asc' | 'desc';
} = {}): Promise<ModelsResponse> {
  console.log('fetchModels: Called with params:', { page, searchTerm, filters, orderBy, order });
  
  // Build filter parameters for API Platform
  const extraParams: Record<string, string | number | boolean> = {};
  
  // Handle individual field filters
  Object.entries(filters).forEach(([key, value]) => {
    if (value && value.trim()) {
      console.log(`fetchModels: Processing filter ${key}:`, value);
      // For text fields, use partial matching with API Platform filters
      if (key === 'name') {
        extraParams['name[contains]'] = value;
      } else if (key === 'brandName') {
        extraParams['brandName[contains]'] = value;
      } else if (key === 'brand') {
        extraParams['brand.name[contains]'] = value;
      } else if (key === 'active') {
        extraParams['active'] = value === 'true';
      } else if (key === 'sequence') {
        extraParams['sequence'] = parseInt(value);
      }
      // For other exact matches
      else {
        extraParams[key] = value;
      }
    }
  });

  console.log('fetchModels: Calling fetchEntities with entity "models" and params:', extraParams);

  return await fetchEntities({
    entity: 'models',
    page,
    partial: false, // Required for hydra:totalItems in API Platform 2.5.7
    searchTerm,
    orderBy,
    order,
    extraParams
  });
}

function getToken() {
  if (typeof window !== 'undefined') {
    // Try to get token from auth_token first (Jotai store)
    try {
      const stored = localStorage.getItem('auth_token');
      if (stored && stored !== 'null') {
        const parsedToken = JSON.parse(stored);
        return parsedToken;
      }
    } catch (e) {
      // Fallback to token key
    }

    // Check localStorage for 'token' key
    try {
      const token = localStorage.getItem('token');
      if (token && token !== 'null') {
        return token;
      }
    } catch (e) {
      // Continue to cookies
    }

    // Fallback to cookies
    const cookies = document.cookie.split(';');
    for (let cookie of cookies) {
      const [name, value] = cookie.trim().split('=');
      if (name === 'token') {
        return value;
      }
    }
  }
  return null;
}

export async function createModel(modelData: Partial<Model>): Promise<Model> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  // Create BreezeJS-style entity with the correct format for the backend
  const entity = {
    name: modelData.name,
    brandName: modelData.brandName,
    sequence: modelData.sequence || 0,
    active: modelData.active ?? true,
    // BreezeJS entity metadata
    entityAspect: {
      entityTypeName: "Model:#App.Entity.Modelling",
      entityState: "Added",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "models"
    }
  };

  // Remove undefined fields
  Object.keys(entity).forEach(key => {
    if (key !== 'entityAspect' && entity[key] === undefined) {
      delete entity[key];
    }
  });

  // Create the save bundle structure expected by the backend
  const saveBundle = {
    entities: [entity]
  };

  console.log('Attempting model creation with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Model creation failed:', errorText);
    throw new Error(`Failed to create model: ${response.statusText}`);
  }

  const result = await response.json();
  console.log('Model creation result:', result);

  // Return the first entity from the response
  return result.Entities?.[0] || result.entities?.[0] || result;
}

export async function updateModel(id: string, modelData: Partial<Model>): Promise<Model> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = getToken();

  // Create BreezeJS-style entity with the correct format for the backend
  const entity = {
    id: id,
    name: modelData.name,
    brandName: modelData.brandName,
    sequence: modelData.sequence || 0,
    active: modelData.active ?? true,
    // BreezeJS entity metadata
    entityAspect: {
      entityTypeName: "Model:#App.Entity.Modelling",
      entityState: "Modified",
      originalValuesMap: {},
      autoGeneratedKey: null,
      defaultResourceName: "models"
    }
  };

  // Remove undefined fields
  Object.keys(entity).forEach(key => {
    if (key !== 'entityAspect' && entity[key] === undefined) {
      delete entity[key];
    }
  });

  // Create the save bundle structure expected by the backend
  const saveBundle = {
    entities: [entity]
  };

  console.log('Attempting model update with BreezeJS SaveBundle:', JSON.stringify(saveBundle, null, 2));

  const response = await fetch(`${API_URL}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/ld+json',
      'Accept': 'application/ld+json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
    body: JSON.stringify(saveBundle),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Model update failed:', errorText);
    throw new Error(`Failed to update model: ${response.statusText}`);
  }

  const result = await response.json();
  console.log('Model update result:', result);

  // Return the first entity from the response
  return result.Entities?.[0] || result.entities?.[0] || result;
}

export async function deleteModel(id: string): Promise<void> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
  const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null;

  const response = await fetch(`${API_URL}/models/${id}`, {
    method: 'DELETE',
    headers: {
      'Accept': 'application/ld+json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    credentials: 'include',
  });

  if (!response.ok) {
    throw new Error(`Failed to delete model: ${response.statusText}`);
  }
}

/**
 * Get the total count of models (for pagination display)
 */
export async function fetchModelCount(): Promise<number> {
  try {
    console.log('📊 fetchModelCount: Getting total model count');

    // Get total count using minimal data transfer (limit=1) with full pagination metadata
    const result = await fetchEntities({
      entity: 'models',
      page: 1,
      partial: false, // Required for hydra:totalItems in API Platform 2.5.7
      extraParams: {
        'limit': 1, // Minimize data transfer
      },
    });

    // Return the total count if available
    if (result['hydra:totalItems'] !== undefined && result['hydra:totalItems'] !== null) {
      console.log('📊 Got total model count from API:', result['hydra:totalItems']);
      return result['hydra:totalItems'];
    }

    console.warn('📊 Could not get model count from API, using fallback');
    return 0;
  } catch (error) {
    console.error('📊 Error fetching model count:', error);
    return 0;
  }
}